### ISSUE TITLE
Bug on DMF pages

### ISSUE THREAD

**Issue by qfritz** [qonto/database-monitoring-framework#33]
Display is broken in DMF pages 
https://qonto.github.io/database-monitoring-framework/latest/

**Comment by qfritz** [comment]
Update: we are working on it.

**Comment by vmercierfr** [comment]
Problem is not fixed.

A v0.2.1 tag was created instead of 0.2.1. Tag was deleted and website were regenerated but for some reason, some Github pages were in cache on Github servers with outdated version.

I just unpublish & restarted the CI to fix it.
